"""GDAL color-relief exporter for Palettize."""

from __future__ import annotations

import logging
from collections.abc import Mapping
from typing import Any, ClassVar

from palettize.core import Colormap, ScalingFunction
from palettize.exceptions import ExporterOptionError

from ._base import NUM_COLORS_OPT, BaseExporter
from ._options import Opt, OptionSpec

logger = logging.getLogger(__name__)


def _parse_rgba(value: Any) -> tuple[int, int, int, int]:
    """Parse an RGBA option given as a tuple/list or a 'r,g,b,a' string."""
    if isinstance(value, str):
        parts = [p.strip() for p in value.split(",")]
    elif isinstance(value, (list, tuple)):
        parts = list(value)  # type: ignore[assignment]
    else:
        raise ExporterOptionError(
            f"Option 'nodata_color' must be an RGBA tuple or 'r,g,b,a' string. Got: {value!r}"
        )

    if len(parts) != 4:
        raise ExporterOptionError(
            f"Option 'nodata_color' needs exactly 4 components. Got: {value!r}"
        )
    try:
        components = [int(p) for p in parts]
    except (TypeError, ValueError):
        raise ExporterOptionError(
            f"Option 'nodata_color' components must be integers. Got: {value!r}"
        ) from None
    if any(not 0 <= c <= 255 for c in components):
        raise ExporterOptionError(
            f"Option 'nodata_color' components must be in 0-255. Got: {value!r}"
        )
    return (components[0], components[1], components[2], components[3])


class GdalExporter(BaseExporter):
    """GDAL ``color-relief`` text files, as consumed by ``gdaldem``."""

    uses_domain: ClassVar[bool] = True
    uses_scaler: ClassVar[bool] = True

    options: ClassVar[OptionSpec] = OptionSpec(
        NUM_COLORS_OPT,
        Opt("nodata", bool, True, "Emit a nodata line."),
        Opt(
            "nodata_value",
            str,
            None,
            "Nodata value. Defaults to GDAL's 'nv' keyword when nodata is enabled.",
        ),
        Opt(
            "nodata_color",
            str,
            (0, 0, 0, 0),
            "Nodata RGBA color as 'r,g,b,a'.",
            parser=_parse_rgba,
        ),
        Opt("precision", int, None, "Decimal places for data values.", minimum=0),
        Opt("verbose", bool, False, "Include a descriptive comment header."),
        Opt("scale_type", str, "unknown", "Scaler name recorded in the header."),
    )

    @property
    def identifier(self) -> str:
        return "gdal"

    @property
    def name(self) -> str:
        return "GDAL Color Relief Text"

    @property
    def default_file_extension(self) -> str:
        return "txt"

    def export(
        self,
        colormap: Colormap,
        scaler: ScalingFunction,
        domain_min: float,
        domain_max: float,
        options: Mapping[str, Any] | None = None,
    ) -> str:
        """Export as ``<value> <R> <G> <B> <A>`` lines, one per color step."""
        opts = self.resolve_options(options)
        self.validate_domain(domain_min, domain_max)
        precision = opts["precision"]

        lines: list[str] = []
        if opts["verbose"]:
            lines.append("# GDAL Color Relief File generated by Palettize\n")
            if colormap.name:
                lines.append(f"# Colormap name: {colormap.name}\n")
            lines.append(f"# Domain: [{domain_min}, {domain_max}], Scaler: {opts['scale_type']}\n")
            lines.append(f"# Interpolation Space for Colormap: {colormap.interpolation_space}\n")

        if opts["nodata"]:
            nodata_value = opts["nodata_value"] if opts["nodata_value"] is not None else "nv"
            r, g, b, a = opts["nodata_color"]
            lines.append(f"{nodata_value} {r} {g} {b} {a}\n")

        for data_value, color in self.sample_scaled(
            colormap, scaler, opts["num_colors"], domain_min, domain_max
        ):
            r, g, b, a = color
            value = round(data_value, precision) if precision is not None else data_value
            lines.append(f"{value} {r} {g} {b} {a}\n")

        return "".join(lines)
